### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by shihabmi7** [cloudamqp/android-example#1]
I found error after run the projetc.

`FATAL EXCEPTION: main
                                                               Process: com.cloudamqp, PID: 24570
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cloudamqp/com.cloudamqp.androidexample.ActivityHome}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                                   at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:207)
                                                                   at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:266)
                                                                   at com.cloudamqp.androidexample.ActivityHome.setupConnectionFactory(ActivityHome.java:89)
                                                                   at com.cloudamqp.androidexample.ActivityHome.onCreate(ActivityHome.java:35)
                                                                   at android.app.Activity.performCreate(Activity.java:6237)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at`

**Comment by carlhoerberg** [comment]
You haven't set an URI, the URI can't be nil that you give to ConnectionFactory.setUri
