### ISSUE TITLE
Error while making a FCM notification request.

### ISSUE THREAD

**Issue by kohli6010** [cloudamqp/android-example#6]
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property code of Error which has only a getter
    at C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\channel.js:227:16
    at Channel.accept (C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\channel.js:188:14)     
    at Connection.mainAccept [as accept] (C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\connection.js:64:33)
    at Socket.go (C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\connection.js:478:48)       
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Connection.emit (events.js:198:13)
    at Connection.C.onSocketError (C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\connection.js:353:10)
    at Connection.emit (events.js:198:13)
    at Socket.go (C:\Users\Rahul\Desktop\NotificationService\node_modules\amqplib\lib\connection.js:481:12)       
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by kohli6010** [comment]
I am trying to send notification using cloudAMQP and Firebase-admin but the above error comes again and again.
